FROM arnislielturks/nginx-php-supervisor:1
RUN apt install libmcrypt-dev mysql-client php7-fileinfo php7-tokenizer \
 php7-xmlwriter php7-mbstring php7-dom php7-intl php7-curl php7-zip shadow

RUN curl --silent --show-error https://getcomposer.org/installer | php

# Configure nginx
COPY docker/nginx.conf /etc/nginx/nginx.conf

# Configure PHP-FPM
COPY docker/fpm-pool.conf /etc/php7/php-fpm.d/zzz_custom.conf


# Configure supervisord
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY docker/php.ini /etc/php7/conf.d/zzz_custom.ini

# Add application
RUN mkdir -p /var/www/html
WORKDIR /var/www/html
RUN curl --silent --show-error https://download.docker.com/linux/static/stable/x86_64/docker-18.09.1.tgz --output docker.tgz
RUN tar -xf docker.tgz && cp docker/docker /usr/bin/docker && rm -R docker

COPY . /var/www/html

ENV DB_HOST=192.168.68.161
ENV DB_NAME=scoreboard
ENV DB_USER=scoreboard
ENV DB_PASSWORD=FvMTAR71wmwvhHzu

RUN php composer.phar install
RUN php artisan migrate
RUN mkdir /var/scoreboard.com/

VOLUME /var/run/docker.sock

EXPOSE 80 443
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
